### ISSUE TITLE
enable search

### ISSUE THREAD

**Issue by mattsouth** [chairuosen/vue-ace-editor-demo#2]
Is there a way to enable search in this packaging of ace?  If I [ctrl]+[f] in the demo then the console shows:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND (ext-searchbox.js:1)
```
This is with chromium and firefox

**Comment by chairuosen** [comment]
require('brace/ext/searchbox');

**Comment by mattsouth** [comment]
perfect, thanks!
